apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: leaderelection
  name: leaderelection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leaderelection
  template:
    metadata:
      labels:
        app: leaderelection
    spec:
      automountServiceAccountToken: true
      serviceAccount: leaderelection-sa
      containers:
      - image: domiwei/elect:latest
        name: leaderelection
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
